name: HolidayMakers
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.3
  dropdown_search: ^6.0.1
  intl: ^0.20.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  intl_phone_number_input: ^0.7.4
  flutter_html: ^3.0.0-beta.2
  # razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  icons_launcher: ^3.0.1
  app_links: ^6.4.0
  introduction_screen: ^3.1.17
  webview_flutter: ^4.10.0
  xml: ^6.5.0
  get: ^4.7.2
  provider: ^6.1.4
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  open_file: ^3.5.10
  country_code_picker: ^3.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - img/
